//
// Created by bigfoot on 2023/5/16.
//

#include "internal.h"

#define ESCAPE_ESC "\x1b"

efi_input_key_escape_map escape_map[]={
	{.escape=ESCAPE_ESC"[A",     .map={.scan_code=SCAN_UP,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[B",     .map={.scan_code=SCAN_DOWN,       .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[C",     .map={.scan_code=SCAN_RIGHT,      .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[D",     .map={.scan_code=SCAN_LEFT,       .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[F",     .map={.scan_code=SCAN_END,        .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[G",     .map={.scan_code=SCAN_PAGE_DOWN,  .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[H",     .map={.scan_code=SCAN_HOME,       .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[I",     .map={.scan_code=SCAN_PAGE_UP,    .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[K",     .map={.scan_code=SCAN_END,        .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[L",     .map={.scan_code=SCAN_INSERT,     .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[M",     .map={.scan_code=SCAN_F1,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[N",     .map={.scan_code=SCAN_F2,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[O",     .map={.scan_code=SCAN_F3,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[P",     .map={.scan_code=SCAN_F4,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[Q",     .map={.scan_code=SCAN_F5,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[R",     .map={.scan_code=SCAN_F6,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[S",     .map={.scan_code=SCAN_F7,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[T",     .map={.scan_code=SCAN_F8,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[U",     .map={.scan_code=SCAN_F9,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[V",     .map={.scan_code=SCAN_F10,        .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[W",     .map={.scan_code=SCAN_F11,        .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[X",     .map={.scan_code=SCAN_DELETE,     .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[@",     .map={.scan_code=SCAN_INSERT,     .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[?",     .map={.scan_code=SCAN_PAGE_UP,    .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[/",     .map={.scan_code=SCAN_PAGE_DOWN,  .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[A",    .map={.scan_code=SCAN_F1,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[B",    .map={.scan_code=SCAN_F2,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[C",    .map={.scan_code=SCAN_F3,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[D",    .map={.scan_code=SCAN_F4,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[E",    .map={.scan_code=SCAN_F5,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[2~",   .map={.scan_code=SCAN_INSERT,     .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[3~",   .map={.scan_code=SCAN_DELETE,     .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[5~",   .map={.scan_code=SCAN_PAGE_UP,    .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[6~",   .map={.scan_code=SCAN_PAGE_DOWN,  .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[11~",  .map={.scan_code=SCAN_F1,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[12~",  .map={.scan_code=SCAN_F2,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[13~",  .map={.scan_code=SCAN_F3,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[14~",  .map={.scan_code=SCAN_F4,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[15~",  .map={.scan_code=SCAN_F5,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[17~",  .map={.scan_code=SCAN_F6,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[18~",  .map={.scan_code=SCAN_F7,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[19~",  .map={.scan_code=SCAN_F8,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[20~",  .map={.scan_code=SCAN_F9,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[21~",  .map={.scan_code=SCAN_F10,        .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[23~",  .map={.scan_code=SCAN_F11,        .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"[[24~",  .map={.scan_code=SCAN_F12,        .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"OM",     .map={.scan_code=SCAN_F10,        .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"OP",     .map={.scan_code=SCAN_F1,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"OQ",     .map={.scan_code=SCAN_F2,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"OR",     .map={.scan_code=SCAN_F3,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"OS",     .map={.scan_code=SCAN_F4,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"OT",     .map={.scan_code=SCAN_F5,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"OU",     .map={.scan_code=SCAN_F6,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"OV",     .map={.scan_code=SCAN_F7,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"OW",     .map={.scan_code=SCAN_F8,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"OX",     .map={.scan_code=SCAN_F9,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"OY",     .map={.scan_code=SCAN_F10,        .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"OZ",     .map={.scan_code=SCAN_F11,        .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"O[",     .map={.scan_code=SCAN_F12,        .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"Ow",     .map={.scan_code=SCAN_F3,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"Ox",     .map={.scan_code=SCAN_F4,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"Ot",     .map={.scan_code=SCAN_F5,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"Ou",     .map={.scan_code=SCAN_F6,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"Oq",     .map={.scan_code=SCAN_F7,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"Or",     .map={.scan_code=SCAN_F8,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"Op",     .map={.scan_code=SCAN_F9,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"h",      .map={.scan_code=SCAN_HOME,       .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"k",      .map={.scan_code=SCAN_END,        .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"1",      .map={.scan_code=SCAN_F1,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"2",      .map={.scan_code=SCAN_F2,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"3",      .map={.scan_code=SCAN_F3,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"4",      .map={.scan_code=SCAN_F4,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"5",      .map={.scan_code=SCAN_F5,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"6",      .map={.scan_code=SCAN_F6,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"7",      .map={.scan_code=SCAN_F7,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"8",      .map={.scan_code=SCAN_F8,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"9",      .map={.scan_code=SCAN_F9,         .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"0",      .map={.scan_code=SCAN_F10,        .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"!",      .map={.scan_code=SCAN_F11,        .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"@",      .map={.scan_code=SCAN_F12,        .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"+",      .map={.scan_code=SCAN_INSERT,     .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"-",      .map={.scan_code=SCAN_DELETE,     .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"?",      .map={.scan_code=SCAN_PAGE_UP,    .unicode_char=CHAR_NULL}},
	{.escape=ESCAPE_ESC"/",      .map={.scan_code=SCAN_PAGE_DOWN,  .unicode_char=CHAR_NULL}},
	{"",{0,0}}
};
